export const SERVICES_CATALOG = [
  { name: "Rock / Gravel", unit: "ton", defaultPrice: 0 },
  { name: "Mulch", unit: "cu yd", defaultPrice: 0 },
  { name: "Topsoil", unit: "cu yd", defaultPrice: 0 },
  { name: "Sod Install", unit: "sq ft", defaultPrice: 0 },
  { name: "Mowing", unit: "visit", defaultPrice: 0 },
  { name: "Edging", unit: "linear ft", defaultPrice: 0 },
  { name: "Weed Control", unit: "sq ft", defaultPrice: 0 },
  { name: "Tree Trimming", unit: "tree", defaultPrice: 0 },
  { name: "Bush Trimming", unit: "bush", defaultPrice: 0 },
  { name: "Leaf Cleanup", unit: "visit", defaultPrice: 0 },
  { name: "Flower Bed Install", unit: "sq ft", defaultPrice: 0 },
  { name: "Retaining Wall", unit: "linear ft", defaultPrice: 0 },
  { name: "French Drain", unit: "linear ft", defaultPrice: 0 },
  { name: "Patio / Pavers", unit: "sq ft", defaultPrice: 0 },
  { name: "Fence Install", unit: "linear ft", defaultPrice: 0 },
  { name: "Irrigation Install", unit: "zone", defaultPrice: 0 },
  { name: "Aeration", unit: "sq ft", defaultPrice: 0 },
  { name: "Overseeding", unit: "sq ft", defaultPrice: 0 },
  { name: "Pressure Wash", unit: "sq ft", defaultPrice: 0 },
  { name: "Snow Removal", unit: "visit", defaultPrice: 0 },
  { name: "Gutter Cleaning", unit: "visit", defaultPrice: 0 },
  { name: "Debris Hauling", unit: "load", defaultPrice: 0 },
];

export const MATERIAL_CATALOG = [
  { name: "Mulch", density: 0.37, note: "Mulch is usually ordered by cubic yard." },
  { name: "Gravel (pea)", density: 0.7, note: "Pea gravel: ~2,800 lb/yd³. Order 10% extra." },
  { name: "Gravel (crushed)", density: 0.75, note: "Crushed stone: ~3,000 lb/yd³." },
  { name: "River Rock", density: 0.65, note: "River rock: ~2,600 lb/yd³." },
  { name: "Topsoil", density: 0.55, note: "Topsoil: ~2,200 lb/yd³." },
  { name: "Sand", density: 0.72, note: "Sand: ~2,900 lb/yd³." },
  { name: "Compost", density: 0.4, note: "Compost: ~1,600 lb/yd³." },
  { name: "Decomposed Granite", density: 0.7, note: "DG: ~2,800 lb/yd³." },
];